name: dialog_presenter
description: Easily create and queue dialogs.
version: 1.0.1
homepage: https://github.com/appnormal/dialog_presenter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  app_settings: ^4.1.8
  flutter:
    sdk: flutter
  image_picker: ^0.8.6

dev_dependencies:
  flutter_lints: ^2.0.0
